services:
  admin:
    build: applications/admin
    container_name: admin
    ports:
      - "5137:5137"
    environment:
      - VITE_ADMIN_PORT=${VITE_ADMIN_PORT}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/admin:/app
    restart: unless-stopped
    networks:
      - immpression-network

  frontend-web:
    build: applications/web-app
    container_name: frontend-web
    ports:
      - "3000:3000"
    environment:
      - VITE_WEB_PORT=${VITE_WEB_PORT}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/web-app:/app
    restart: unless-stopped
    networks:
      - immpression-network

  backend:
    build: applications/backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - CLOUDINARY_API=${CLOUDINARY_API}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_CLOUD=${CLOUDINARY_CLOUD}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/backend:/app
    networks:
      - immpression-network
    depends_on:
      - mongo
    restart: unless-stopped

  frontend-mobile:
    build: applications/mobile-app
    container_name: frontend-mobile
    ports:
      - "19000:19000" # Expo
      - "8081:8081" # Metro
    stdin_open: true # Keeps stdin open for interactive output on startup, allowing expo url and qr code to be displayed
    tty: true # Allocates a pseudo-TTY
    environment:
      - VITE_APP_ENV=${VITE_APP_ENV}
      - EXPO_TOKEN=${EXPO_TOKEN}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/mobile-app:/app
    restart: unless-stopped
    networks:
      - immpression-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/mongo_data
    restart: unless-stopped
    networks:
      - immpression-network

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  immpression-network:
    driver: bridge
