services:
  admin:
    build: applications/admin
    container_name: admin
    ports:
      - "5137:5137"
    environment:
      - VITE_APP_ADMIN_PORT=${VITE_APP_ADMIN_PORT}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/admin:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - immpression-network

  frontend-web:
    build: applications/web-app
    container_name: frontend-web
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_WEB_PORT=${VITE_APP_WEB_PORT}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
    volumes:
      - ./applications/web-app:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - immpression-network

  backend:
    build: applications/backend
    container_name: backend
    ports:
      - "4000:4000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
      - CLOUDINARY_API=${CLOUDINARY_API}
      - CLOUDINARY_SECRET=${CLOUDINARY_SECRET}
      - CLOUDINARY_CLOUD=${CLOUDINARY_CLOUD}
      - VITE_APP_ENV=${VITE_APP_ENV}
      - CHOKIDAR_USEPOLLING=${CHOKIDAR_USEPOLLING}
      - VITE_APP_ADMIN_PORT=${VITE_APP_ADMIN_PORT}
      - VITE_APP_WEB_PORT=${VITE_APP_WEB_PORT}
      - MOBILE_PORT=${MOBILE_PORT}
      - HOST_IP=${HOST_IP}
      - STRIPE_PUBLISH_KEY=$(STRIPE_PUBLISH_KEY}
      - STRIPE_SECRET_KEY=$(STRIPE_SECRET_KEY}
    volumes:
      - ./applications/backend:/app
      - /app/node_modules
    networks:
      - immpression-network
    depends_on:
      - mongo
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/mongo_data
    restart: unless-stopped
    networks:
      - immpression-network

  test-runner-backend:
    image: node:18
    container_name: test-runner
    working_dir: /app
    volumes:
      - ./applications/backend:/app
    depends_on:
      - backend
      - mongo
    environment:
      - NODE_ENV=test
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_PUBLISH_KEY=${STRIPE_PUBLISH_KEY}
      - MONGO_URL=${MONGO_URL}
      - JWT_SECRET=${JWT_SECRET}
    command: ["npm", "test"]
    networks:
      - immpression-network

  test-runner-frontend:
    image: node:18
    container_name: test-runner-frontend
    working_dir: /app
    volumes:
      - ./applications/mobile-app:/app
    command: [ "npm", "test" ]
    networks:
      - immpression-network

volumes:
  mongo_data:
    driver: local
    driver_opts:
      type: none
      device: ./data
      o: bind

networks:
  immpression-network:
    driver: bridge
